# app/config.py
import os
from dotenv import load_dotenv

load_dotenv()

IOTHUB_NAME = os.getenv("IOTHUB_NAME")
IOTHUB_POLICY_NAME = os.getenv("IOTHUB_POLICY_NAME")
IOTHUB_POLICY_KEY = os.getenv("IOTHUB_POLICY_KEY")

IOTHUB_EVENTHUB_CONNECTION_STRING = os.getenv("IOTHUB_EVENTHUB_CONNECTION_STRING")
CONSUMER_GROUP = os.getenv("CONSUMER_GROUP")
IOTHUB_EVENTHUB_NAME = os.getenv("IOTHUB_EVENTHUB_NAME")

if not all([IOTHUB_NAME, IOTHUB_POLICY_NAME, IOTHUB_POLICY_KEY, IOTHUB_EVENTHUB_CONNECTION_STRING, CONSUMER_GROUP, IOTHUB_EVENTHUB_NAME]):
    raise RuntimeError("Missing IoT Hub config in .env")
